### ISSUE TITLE
Crashes IE9 and almost completely freezes computer

### ISSUE THREAD

**Issue by axefrog** [doctyper/flexie#10]
Not sure if it requires a specific set of circumstances to do this, but I am happy to demonstrate a layout to you that pretty much causes IE9 to fall over dead while trying very hard to convince the rest of Windows 7 (64 bit) to do the same. Is IE9 compatibility a known problem?

**Comment by doctyper** [comment]
I wouldn't say it's a known problem. IE9 passes all unit tests with flying colors. I will say that until it reaches GM status, IE9 bugs will be low priority for me.

Nevertheless, I'd love to see a sample of the issue you're seeing.

**Comment by axefrog** [comment]
Yes, true. To be fair, it suddenly occurs to me that I don't think I'm the absolute latest IE9 preview either, so I may as well close this one. I'll report it again if it happens in the RTM or if hell freezes over and they actually decide to implement the flexible box model.

**Comment by tcannonfodder** [comment]
Having the same issues. It works for 1 flexible box set, but when I add more than that (around 3), it completely crashes.
