### ISSUE TITLE
Flexie Demo Doesn't Work

### ISSUE THREAD

**Issue by dangayle** [doctyper/flexie#11]
The /demo/ you include with the download doesn't work in at least FF 3.6.15 and Safari 5.0.4

**Comment by doctyper** [comment]
I've just tested the demo and it appears to work fine in these browsers. What exactly is the issue you are having?

**Comment by dangayle** [comment]
Site tested here:
http://www.dangayle.com/doctyper-flexie-d34a00b/demo/

Attached files are firefox and safari
http://dangayle.s3.amazonaws.com/uploads/firefox-flexie.png
http://dangayle.s3.amazonaws.com/uploads/safari-flexie.png

On Thu, Mar 17, 2011 at 2:57 PM, doctyper
reply@reply.github.com
wrote:

**Comment by doctyper** [comment]
Attachments don't come through on Github issues.

## The demo renders fine in FF/Safari on your site. IE is wrong, and that's because the path to flexie.js is wrong. 

Richard Herrera

**Comment by dangayle** [comment]
http://dangayle.s3.amazonaws.com/uploads/firefox-flexie.png http://dangayle.s3.amazonaws.com/uploads/safari-flexie.png

**Comment by dangayle** [comment]
oops, I closed it. Sorry

**Comment by dangayle** [comment]
Also, my bad. I didn't realize it was a vertically oriented demo. I see that now. 
Thanks!
