### ISSUE TITLE
IE9 crashes and doesn't complete the test-case

### ISSUE THREAD

**Issue by dnjreinders-85** [doctyper/flexie#16]
At first my compliments on this javascript 'plugin'. Designing and creating clean HTML will be much easier with the box-options. unfortunately IE9 crashes when the box-flex option is used in the CSS. When I delete the option box-flex from the CSS the browser won't crash; But the box-flex option is just the option I need, so it ain't the best solution to simply remove this option. Here is a small (incomplete) preview of my code.

in Stylesheet:

<pre>
.columns-horizontale{
    width:100%; 
    display: -moz-box;
    display: -webkit-box;
    display: -ms-box;
    display: box;
}

.columns-horizontale > div{
    -webkit-box-flex: 1;
    -moz-box-flex: 1;
    box-flex: 1;
    
    border-right:1px solid #000;
}
</pre>

In HTML

<pre>
&lt;div class="columns-horizontale"&gt;
    &lt;div&gt;column1 &lt;/div&gt;
     &lt;div&gt;column2 &lt;/div&gt;
 &lt;/div&gt;
</pre>

**Comment by davidpadbury** [comment]
I can confirm that IE9 support appears a bit borked - tests fail, playground crashes, my app goes poof. IE6-8 function correctly/well. Using flexie 1.0.0.

Any pointers for how I could help?

**Comment by locks** [comment]
I want to pile on.

# IE9

## Browser Mode: IE9

Frequently crashes the tests for me.
When it doesn't crash, most of the tests have a off-by-one error in the xx axis dimensions.

## Browser Mode: IE7

Passes every test

## Any mode

flexiejs doesn't seem to be working.
Layout isn't correct according to flex-box CSS rules.

**Comment by doctyper** [comment]
Fixed in d5b2ef9. Flexie is once again passing tests in all supported browsers (sans Firefox).
