### ISSUE TITLE
Does this require Selectivizr?

### ISSUE THREAD

**Issue by matthew-dean** [doctyper/flexie#17]
This isn't clear to me.  It says it uses the Selectivizr engine, has lots of references to it, but doesn't state outright whether or not its a necessity.

**Comment by doctyper** [comment]
Nope, it's bundled with the necessary Selectivizr bits.

**Comment by dangayle** [comment]
Could you add that bit to the front page then?

**Comment by doctyper** [comment]
...So you want me to state that the lib doesn't require Selectivizr? Seems odd. It doesn't require Prototype.js either, should I call that out too? :)

**Comment by dangayle** [comment]
It's just that the requirements in the documentation all link to selectivizr.

"How? No setup on your end, just stick Flexie in your markup after your selector engine of choice. (with a link to selectivizr)"

"Requirements. See the things you need to know. (another link to selectivizr)

If the HOW is just "Add flexie to the header of your document", then it should say that. It doesn't currently, that's all.
