### ISSUE TITLE
Featured test case not working in IE7/8

### ISSUE THREAD

**Issue by gekkoh** [doctyper/flexie#18]
The test that is featured on the Flexie homepage ( http://flexiejs.com/test/cases/ie7nomore.com/ ) doesn't seem to be working in IE7 or IE8 but surprisingly, it works in IE6.

Here's a screenshot from Adobe Browser Lab: http://cl.ly/7qGy

**Comment by doctyper** [comment]
Just tested and verified working in IE7/8 on a virtual machine. I'm not familiar with Adobe Browser Lab, but it may be that it either does not have JavaScript enabled for its tests, or it snaps the screenshot before the onload event is fired.

**Comment by gekkoh** [comment]
Good to hear it works! :)

I thought you could rely on a big name like Adobe but I guess they're just as "reliable" as Microsoft ;P
I tested it again using Litmus App and it works fine.

Cheers!
