### ISSUE TITLE
Javascript error when used with media queries

### ISSUE THREAD

**Issue by ollynevard** [doctyper/flexie#20]
I get the following javascript error when using flexie.js with inline media queries:

> Uncaught Syntax error, unrecognized expression: (min-width:768px) {

This is the media query css

``` css
@media only screen and (min-width: 768px) {
  /* flex box css here */
}
```

Works great without media queries though.

**Comment by doctyper** [comment]
Fixed in 7cba432, although please note that I do not make any effort to _understand_ the query. I'm merely suppressing the resulting error.
