### ISSUE TITLE
IE9 throws error on local flexie.js but Playground works

### ISSUE THREAD

**Issue by ccondrup** [doctyper/flexie#24]
I am getting the below error in IE 9.0.8112.16421 on Win7 x64. Both when using the packed and the regular javascript file. Joomla supplies Mootools 1.3.2, but I have also tried jQuery 1.6.4. Tried latest master and the flexie.min.js used in the Playground. Tried browser modes IE7,8,9 and several document standards variations. This very well might be related to my html/css but am not sure where to start looking, so any pointers would be appreciated. I have switched up a lot of the html/css already but this IE error remains. I tried to narrow down my html/css into this paste: http://jsfiddle.net/wQpN8/1/

```
SCRIPT5007: Unable to get value of the property 'length': object is null or undefined 
flexie.js, line 1021 character 15
```

Which would be:

```
function cleanPositioningProperties (children) {
        var i, j, kid, w, h;

        for (i = 0, j = children.length; i < j; i++) {
```

**Comment by drahgon55** [comment]
I was able to fix this myself by adding in this line to cleanPositioningProperties

<pre>
function cleanPositioningProperties(children) {
        var i, j, kid, w, h;

      <h3> if (children == undefined) {
            children = [];
        }</h3>

        for (i = 0, j = children.length; i < j; i++) {
</pre>
