### ISSUE TITLE
Not working(??)

### ISSUE THREAD

**Issue by timmolendijk** [doctyper/flexie#3]
Absolutely loving flexie's concept. But when I open the demos in IE8 they do not seem to be impacted by any means; I mean the pages render as if no flexie was included.

What am I missing?

**Comment by doctyper** [comment]
Not sure. I just cloned a local copy in case my build was different, but everything works as expected.

**Comment by timmolendijk** [comment]
Strange. Check out this screenshot of Opera10. Same for IE8. Guess I must be overlooking something really silly. Do I need to download any dependencies by any chance?

![Opera10](http://files.smartpr.nl/90369224c6e054f6272b12a6a527df30ad386a07/Screen_shot_2010-11-08_at_6.57.02_PM.png)

**Comment by doctyper** [comment]
Ah, I think the problem is you're running it locally. Selectivizr uses Ajax to download and parse the included CSS files. Try running it as a server, using the flexie root as your root.

**Comment by timmolendijk** [comment]
Ah yes that makes sense. Cool, thx!
