### ISSUE TITLE
README is out of date and misleading

### ISSUE THREAD

**Issue by ef4** [doctyper/flexie#43]
The link to the W3C spec at the beginning of the README points to a newer version of the spec that flexie doesn't actually support.

W3C provides versioned URLs, so I think it would be clearer to link directly to the version that you do support.

**Comment by ErickPetru** [comment]
It also would be clearer to explain that Flexie doesn't supports the newer Candidate Recomendation version in the README. Or change the project to add this support (much better).

**Comment by doctyper** [comment]
"Misleading" is a bit strong. At the time of authoring, this polyfill _was_ supporting the latest spec, and the link to the spec was correct. I just never got around to changing the description.

I've updated the README.
