### ISSUE TITLE
Boxes gain height in some cases when content added in IE

### ISSUE THREAD

**Issue by regnix** [doctyper/flexie#9]
Example to clarify :
http://regnix.net/flex/

Fine in FF and Chrome, just IE only tested 7 and 8.

Other than that, excellent work, I wish I knew more JavaScript to fix it myself.

**Comment by ghost** [comment]
I can confirm this problem for IE 9.

**Comment by doctyper** [comment]
Test case 404s. Please re-submit if error is still occurring.

**Comment by ghost** [comment]
Problem persists in IE9 with 1.0.3 unfortunately.
